language: generic 

services:
  - docker

before_script:
  - docker ps

script:
  - docker-compose up -d

after_script:
  - docker-compose down 

notifications:
  email:
    recipients:
      - wilfried.noubissie@facsciences-uy1.cm
    on_success: always
    on_failure: always
